import React, { createContext, useContext, useEffect, useState } from 'react';

type Language = 'id' | 'en' | 'jp' | 'zh' | 'es' | 'ar' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  id: {
    'login.welcome': 'Selamat Datang Kembali.',
    'login.subtitle': 'Akses portal manajemen data Anda',
    'login.email_label': 'Identitas Email',
    'login.password_label': 'Token Keamanan',
    'login.remember_me': 'Percayai perangkat ini',
    'login.forgot_password': 'Pemulihan',
    'login.submit': 'Autentikasi Akses',
    'login.processing': 'Mengotorisasi...',
    'login.footer': 'Portal Aman © 2026 Wahana Data Utama',
    'login.error': 'Email atau kata sandi tidak valid. Silakan coba lagi.',
    'common.loading': '',
    'common.intelligence': 'Intelijen WDU',
    'common.data_business': 'DATA ADALAH BISNIS KAMI.',
    'common.empowering': 'Memberdayakan pengambil keputusan dengan wawasan data real-time dan analitik tingkat lanjut sejak 2006.',
    'services.title.Big Data Analytics': 'Analitik Big Data',
    'services.desc.Big Data Analytics': 'Mengubah data kompleks menjadi wawasan strategis untuk pertumbuhan bisnis Anda.',
    'services.title.Digital Survey': 'Survei Digital',
    'services.desc.Digital Survey': 'Pengumpulan data cepat dan akurat dengan metodologi digital tercanggih.',
    'services.title.IoT Solutions': 'Solusi IoT',
    'services.desc.IoT Solutions': 'Menghubungkan perangkat dan data untuk efisiensi operasional yang lebih cerdas.',
    'services.title.Strategic Consulting': 'Konsultasi Strategis',
    'services.desc.Strategic Consulting': 'Panduan ahli untuk navigasi tantangan bisnis dan peluang masa depan.',
    'services.title.GIS Mapping': 'Pemetaan GIS',
    'services.desc.GIS Mapping': 'Visualisasi data geografis untuk perencanaan dan analisis spasial yang presisi.',
    'services.title.Research & Development': 'Riset & Pengembangan',
    'services.desc.Research & Development': 'Inovasi berkelanjutan didorong oleh penelitian mendalam dan pengujian.',
    'footer.copyright': '© 2026 Wahana Data Utama. Hak cipta dilindungi undang-undang.',
    'footer.address_text': 'Blok AE No. 01, Jl. Terapi Raya, Menteng, Bogor Barat, 16111',
    'common.years_exp': 'TAHUN PENGALAMAN',
    'common.projects': 'Proyek',
    'common.analytics': 'Analitik 24/7',
    'nav.home': 'Beranda',
    'nav.about': 'Tentang Kami',
    'nav.services': 'Layanan',
    'nav.experience': 'Pengalaman',
    'nav.contact': 'Kontak',
    'nav.download_profile': 'Profil Perusahaan',
    'footer.address': 'Alamat Kantor',
    'footer.contact': 'Hubungi Kami',
    'footer.social': 'Media Sosial',
    'footer.privacy': 'Privasi',
    'footer.terms': 'Syarat & Ketentuan',
    'footer.cookies': 'Kebijakan Cookie',
    'experience.hero_title': 'PENGALAMAN KAMI',
    'experience.intro_title': 'Membangun kepercayaan melalui bukti nyata.',
    'home.hero_title': 'Data Terpadu, Solusi Cerdas | Hasil Maksimal',
    'home.hero_content': 'Percayakan kebutuhan riset, analisis data, dan teknologi kepada Wahana Data Utama. Kami mengubah data menjadi wawasan berharga dan solusi praktis yang membantu Anda meraih keunggulan kompetitif di era digital.',
    'home.hero_click': 'Klik untuk melihat visi kami',
    'home.intro_title': 'Memiliki pengalaman yang luas serta didukung oleh tim profesional yang kompeten.',
    'home.stats_projects': 'Proyek Selesai',
    'home.stats_clients': 'Klien Puas',
    'home.stats_efficiency': 'Efisiensi Data',
    'home.stats_support': 'Dukungan 24/7',
    'home.services_title': 'Layanan Kami',
    'home.services_subtitle': 'Solusi Data Terintegrasi',
    'home.services_content': 'Wahana Data Utama berkomitmen untuk membantu bisnis dan organisasi Anda mengelola, menganalisis, dan memanfaatkan data secara optimal.',
    'home.loading_services': 'Memuat Layanan...',
    'home.no_services': 'Layanan tidak tersedia.',
    'home.solution_title': 'Solusi Data',
    'home.trust_title': 'Kepercayaan klien terhadap kami',
    'home.trust_subtitle': 'Dengan pengalaman selama 18 tahun, kami membangun kolaborasi strategis untuk organisasi pemerintah dan juga sektor swasta.',
    'home.gallery_subtitle': 'Potret kegiatan & kolaborasi kami',
    'home.gallery_quote': '"Akurasi data adalah janji kami, kolaborasi adalah kekuatan kami."',
    'home.director_title': 'Direktur Utama',
    'about.hero_title': 'Precision Intelligence',
    'about.intro_subtitle': 'Tentang Kami',
    'about.intro_title': 'Wahana Data Utama',
    'about.mission_title': 'Misi Kami Untuk Anda',
    'about.mission_desc': 'Berkomitmen memberikan solusi data dengan integritas dan dampak luas bagi kemajuan bisnis Anda.',
    'about.vision_label': 'Visi',
    'about.vision_text': 'Menjadi perusahaan penyedia data riset/survei global.',
    'about.mission_label': 'Misi',
    'about.mission_1': 'Melakukan riset, survei dan kajian yang kredibel sesuai kaidah ilmiah untuk menghasilkan data yang akurat, presisi, dan andal.',
    'about.mission_2': 'Mengorganisir sebuah kegiatan dengan akurat, presisi dan andal.',
    'about.mission_3': 'Menjadi perusahaan kreatif yang penuh inovasi, solusi dan gagasan.',
    'about.pillar_1_title': 'Kredibilitas Ilmiah',
    'about.pillar_1_desc': 'Melakukan riset, survei dan kajian yang kredibel sesuai kaidah ilmiah.',
    'about.pillar_2_title': 'Presisi Operasional',
    'about.pillar_2_desc': 'Mengorganisir sebuah kegiatan dengan akurat, presisi dan andal.',
    'about.pillar_3_title': 'Inovasi Kreatif',
    'about.pillar_3_desc': 'Menjadi perusahaan kreatif yang penuh inovasi, solusi dan gagasan.',
    'about.leadership_label': 'Kepemimpinan Kami',
    'about.directors_title': 'Jajaran Direksi',
    'about.data_business_desc': 'Memberdayakan perusahaan global sejak 2006.',
    'about.pro_title': 'Garda Terdepan Profesional Berpengalaman',
    'contact.hero_title': 'HUBUNGI KAMI',
    'contact.intro_title': 'Mari Mulai Sesuatu yang Hebat Bersama.',
    'contact.hero_label': 'Editorial Intelligence',
    'contact.address_label': 'Alamat Kantor',
    'contact.email_label': 'Email',
    'contact.phone_label': 'Telepon',
    'contact.form_title': 'Kirim Pesan',
    'contact.success_title': 'Terima Kasih!',
    'contact.success_message': 'Pesan Anda telah berhasil dikirim. Kami akan segera menghubungi Anda.',
    'contact.send_again': 'Kirim pesan lagi',
    'contact.full_name': 'Nama Lengkap',
    'contact.business_email': 'Email Bisnis',
    'contact.phone_number': 'Nomor Telepon',
    'contact.message': 'Pesan',
    'contact.message_placeholder': 'Bagaimana kami dapat membantu bisnis Anda hari ini?',
    'contact.sending': 'Mengirim...',
    'contact.send_button': 'Kirim Pesan Sekarang',
    'contact.privacy_note': 'Data Anda tersimpan dengan aman sesuai kebijakan privasi kami.',
    'contact.hero_description': 'Kami di sini untuk mendengarkan visi Anda dan memberikan solusi teknologi yang tepat sasaran. Jangan ragu untuk menghubungi kami untuk konsultasi awal atau sekadar bertanya mengenai layanan kami.',
    'contact.intro_description': 'Tim ahli kami siap memberikan respons cepat untuk setiap pertanyaan Anda mengenai transformasi digital dan manajemen data cerdas.',
    'experience.track_record': 'REKAM JEJAK KAMI',
    'experience.headquarter': 'Kantor Pusat WDU',
    'experience.quality_assured': 'Kualitas Terjamin',
    'experience.data_accurate': 'Data akurat untuk keputusan strategis.',
    'experience.milestones_title': 'Pencapaian',
    'experience.milestones_subtitle': 'Mitra Strategis & Kolaborasi Nasional',
    'experience.partners_count': 'Mitra',
    'experience.syncing': 'Sinkronisasi Data Mitra...',
    'services.intro_subtitle': 'Layanan Kami',
    'services.intro_title': 'Jelajahi beragam solusi terbaik dengan menggunakan layanan kami!',
    'services.intro_description': 'Kami dengan senang hati siap membantu memenuhi kebutuhan Anda melalui layanan terbaik yang kami sediakan.',
    'services.no_services': 'Belum ada layanan yang tersedia saat ini.',    'services.hero_content': 'Hadirkan transformasi nyata untuk bisnis Anda melalui rangkaian solusi cerdas berbasis data, teknologi mutakhir, dan analitik mendalam. Kami berdedikasi untuk membantu Anda mencapai efisiensi dan potensi maksimal.',
    'services.intro_content_1': 'Hadirkan transformasi nyata untuk bisnis Anda melalui rangkaian solusi cerdas berbasis data, teknologi mutakhir, dan analitik mendalam.',
    'services.intro_content_2': 'Jelajahi beragam solusi terbaik dengan menggunakan layanan kami!',
    'services.intro_content_3': 'Kami dengan senang hati siap membantu memenuhi kebutuhan Anda melalui layanan terbaik yang kami sediakan. Jangan ragu untuk mengandalkan kami dalam memberikan solusi yang tepat untuk Anda!',
    'experience.content_1': 'Sejak didirikan pada tahun 2006, Wahana Data Utama telah mengukir perjalanan panjang sebagai penyedia layanan riset dan data terdepan di Indonesia. Pengalaman kami dalam memanfaatkan teknologi terkini seperti big data analytics, survei, dan Internet of Things (IoT) memungkinkan kami untuk memberikan solusi yang relevan dan inovatif di berbagai sektor. Kami telah berkolaborasi dengan berbagai industries, mulai dari koperasi dan UKM, agribisnis, hingga periklanan digital, untuk menghadirkan layanan berbasis cloud yang cepat dan akurat. Pengalaman kami juga mencakup penerapan machine learning dalam analisis prediktif, membantu klien menghadapi tantangan bisnis yang terus berkembang. Dengan pengalaman luas di bidang riset sosial-politik, ekonomi pembangunan, dan manajemen pemasaran, kami terus berkomitmen untuk mendukung klien dalam menciptakan keunggulan kompetitif yang berkelanjutan di era Revolusi Industri 5.0.',
    'experience.content_2': 'Dengan komitmen yang kuat terhadap inovasi dan keakuratan data, Wahana Data Utama siap menjadi mitra terpercaya bagi bisnis dan organisasi dalam mengambil keputusan berbasis informasi. Di era digital yang semakin kompleks, kami terus berinovasi dengan teknologi terkini untuk menghadirkan solusi yang relevan, akurat, dan berdampak nyata.',
    'experience.content_3': 'Kepercayaan klien adalah prioritas utama kami, dan dengan pengalaman bertahun-tahun serta tim profesional yang andal, kami berkomitmen untuk membantu berbagai sektor mengoptimalkan strategi bisnis mereka.',
    'experience.content_4': 'Bersama Wahana Data Utama, Anda tidak hanya mendapatkan data, tetapi juga wawasan strategis yang mendorong pertumbuhan dan kesuksesan jangka panjang. Mari melangkah ke masa depan dengan strategi yang lebih cerdas, efisien, dan berdaya saing tinggi!',
    'role.KOMISARIS UTAMA': 'KOMISARIS UTAMA',
    'role.DIREKTUR UTAMA': 'DIREKTUR UTAMA',
    'role.DIREKTUR': 'DIREKTUR',
    'services.title.Riset Pasar': 'Riset Pasar',
    'services.desc.Riset Pasar': 'Jelajahi peluang baru dan pahami tren pasar dengan riset pasar yang mendalam.',
    'services.title.Riset Data': 'Riset Data',
    'services.desc.Riset Data': 'Pengolahan data primer dan sekunder untuk menghasilkan wawasan strategis.',
    'services.title.Analisis Data': 'Analisis Data',
    'services.desc.Analisis Data': 'Transformasi raw data menjadi aset strategis melalui pemrosesan dan validasi tingkat lanjut.',
    'services.title.Survei': 'Survei',
    'services.desc.Survei': 'Pengumpulan data lapangan yang akurat dengan metodologi ilmiah yang teruji.',
    'services.title.Event Organizer': 'Event Organizer',
    'services.desc.Event Organizer': 'Penyelenggaraan acara profesional yang berfokus pada detail dan dampak yang berkesan.',
    'services.title.Konsultasi IT': 'Konsultasi IT',
    'services.desc.Konsultasi IT': 'Konsultasi teknologi strategis untuk mengoptimalkan infrastruktur digital bisnis Anda.',
    'project.info_title': 'Informasi Kerjasama',
    'project.desc_1': 'telah menjalin kerjasama strategis dalam berbagai proyek riset, pengembangan sistem, dan analisis data. Melalui kolaborasi ini, kami membantu mitra kami dalam mencapai efisiensi operasional dan pengambilan keputusan berbasis data yang akurat.',
    'project.desc_2': 'Proyek ini melibatkan implementasi metodologi riset terkini dan pemanfaatan teknologi analisis data untuk memberikan wawasan mendalam yang relevan dengan tantangan industri saat ini.',
    'project.quick_info': 'Informasi Cepat',
    'project.category_label': 'Kategori',
    'project.year_label': 'Tahun',
    'project.status_label': 'Status',
    'project.status_done': 'Selesai',
    'project.other_title': 'Kerjasama Lainnya',
    'project.back_to_experience': 'Kembali ke Pengalaman',
    'project.hero_title': 'Detail Proyek',
    'category.Research & Development': 'Riset & Pengembangan'
  },
  en: {
    'login.welcome': 'Welcome Back.',
    'login.subtitle': 'Access your data management portal',
    'login.email_label': 'Email Identity',
    'login.password_label': 'Secure Token',
    'login.remember_me': 'Trust this device',
    'login.forgot_password': 'Recovery',
    'login.submit': 'Authenticate Access',
    'login.processing': 'Authorizing...',
    'login.footer': 'Secure Portal © 2026 Wahana Data Utama',
    'login.error': 'Invalid email or password. Please try again.',
    'common.loading': 'Please wait a moment...',
    'common.intelligence': 'WDU Intelligence',
    'common.data_business': 'DATA IS OUR BUSINESS.',
    'common.empowering': 'Empowering decision-makers with real-time data insights and advanced analytics since 2006.',
    'services.title.Big Data Analytics': 'Big Data Analytics',
    'services.desc.Big Data Analytics': 'Transforming complex data into strategic insights for your business growth.',
    'services.title.Digital Survey': 'Digital Survey',
    'services.desc.Digital Survey': 'Fast and accurate data collection with cutting-edge digital methodologies.',
    'services.title.IoT Solutions': 'IoT Solutions',
    'services.desc.IoT Solutions': 'Connecting devices and data for smarter operational efficiency.',
    'services.title.Strategic Consulting': 'Strategic Consulting',
    'services.desc.Strategic Consulting': 'Expert guidance for navigating business challenges and future opportunities.',
    'services.title.GIS Mapping': 'GIS Mapping',
    'services.desc.GIS Mapping': 'Geographic data visualization for precision planning and spatial analysis.',
    'services.title.Research & Development': 'Research & Development',
    'services.desc.Research & Development': 'Continuous innovation driven by in-depth research and testing.',
    'footer.copyright': '© 2026 Wahana Data Utama. All rights reserved.',
    'footer.address_text': 'Blok AE No. 01, Jl. Terapi Raya, Menteng, Bogor Barat, 16111',
    'common.years_exp': 'YEARS EXPERIENCE',
    'common.projects': 'Projects',
    'common.analytics': '24/7 Analytics',
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.services': 'Services',
    'nav.experience': 'Experience',
    'nav.contact': 'Contact',
    'nav.download_profile': 'Company Profile',
    'footer.address': 'Office Address',
    'footer.contact': 'Contact Us',
    'footer.social': 'Social Media',
    'footer.privacy': 'Privacy',
    'footer.terms': 'Terms',
    'footer.cookies': 'Cookies',
    'experience.hero_title': 'OUR EXPERIENCE',
    'experience.intro_title': 'Building trust through real evidence.',
    'home.hero_title': 'Unified Data, Smart Solutions | Maximum Results',
    'home.hero_content': 'Entrust your research, data analysis, and technology needs to Wahana Data Utama. We transform data into valuable insights and practical solutions that help you gain a competitive edge in the digital era.',
    'home.hero_click': 'Click to explore our vision',
    'home.intro_title': 'Extensive experience backed by a competent professional team.',
    'home.stats_projects': 'Projects Completed',
    'home.stats_clients': 'Satisfied Clients',
    'home.stats_efficiency': 'Data Efficiency',
    'home.stats_support': '24/7 Support',
    'home.services_title': 'Our Services',
    'home.services_subtitle': 'Integrated Data Solutions',
    'home.services_content': 'Wahana Data Utama is committed to helping your business and organization manage, analyze, and utilize data optimally.',
    'home.loading_services': 'Loading Services...',
    'home.no_services': 'No services available.',
    'home.solution_title': 'Data Solutions',
    'home.trust_title': 'Client Trust in Us',
    'home.trust_subtitle': 'With 18 years of experience, we build strategic collaborations for government organizations and the private sector.',
    'home.gallery_subtitle': 'Portraits of our activities & collaborations',
    'home.gallery_quote': '"Data accuracy is our promise, collaboration is our strength."',
    'home.director_title': 'President Director',
    'about.hero_title': 'Precision Intelligence',
    'about.intro_subtitle': 'About Us',
    'about.intro_title': 'Wahana Data Utama',
    'about.mission_title': 'Our Mission for You',
    'about.mission_desc': 'Committed to providing data solutions with integrity and broad impact for your business progress.',
    'about.vision_label': 'Vision',
    'about.vision_text': 'To be a global research/survey data provider company.',
    'about.mission_label': 'Mission',
    'about.mission_1': 'Conduct credible research, surveys, and studies according to scientific rules to produce accurate, precise, and reliable data.',
    'about.mission_2': 'Organize an activity accurately, precisely, and reliably.',
    'about.mission_3': 'To be a creative company full of innovation, solutions, and ideas.',
    'about.pillar_1_title': 'Scientific Credibility',
    'about.pillar_1_desc': 'Conduct credible research, surveys, and studies according to scientific rules.',
    'about.pillar_2_title': 'Operational Precision',
    'about.pillar_2_desc': 'Organize an activity accurately, precisely, and reliably.',
    'about.pillar_3_title': 'Creative Innovation',
    'about.pillar_3_desc': 'To be a creative company full of innovation, solutions, and ideas.',
    'about.leadership_label': 'Our Leadership',
    'about.directors_title': 'Board of Directors',
    'about.data_business_desc': 'Empowering global enterprises since 2006.',
    'about.pro_title': 'The Frontline of Experienced Professionals',
    'contact.hero_title': 'CONTACT US',
    'contact.intro_title': 'Let\'s Start Something Great Together.',
    'contact.hero_label': 'Editorial Intelligence',
    'contact.address_label': 'Office Address',
    'contact.email_label': 'Email',
    'contact.phone_label': 'Phone',
    'contact.form_title': 'Send Message',
    'contact.success_title': 'Thank You!',
    'contact.success_message': 'Your message has been sent successfully. We will contact you soon.',
    'contact.send_again': 'Send another message',
    'contact.full_name': 'Full Name',
    'contact.business_email': 'Business Email',
    'contact.phone_number': 'Phone Number',
    'contact.message': 'Message',
    'contact.message_placeholder': 'How can we help your business today?',
    'contact.sending': 'Sending...',
    'contact.send_button': 'Send Message Now',
    'contact.privacy_note': 'Your data is stored securely in accordance with our privacy policy.',
    'contact.hero_description': 'We are here to listen to your vision and provide technology solutions that are right on target. Feel free to contact us for an initial consultation or just to ask about our services.',
    'contact.intro_description': 'Our team of experts is ready to provide a quick response to any of your questions regarding digital transformation and smart data management.',
    'experience.track_record': 'OUR TRACK RECORD',
    'experience.headquarter': 'WDU Headquarter',
    'experience.quality_assured': 'Quality Assured',
    'experience.data_accurate': 'Accurate data for strategic decisions.',
    'experience.milestones_title': 'Milestones',
    'experience.milestones_subtitle': 'Strategic Partners & National Collaboration',
    'experience.partners_count': 'Partners',
    'experience.syncing': 'Synchronizing Partners Data...',
    'services.intro_subtitle': 'Our Services',
    'services.intro_title': 'Explore various top solutions using our services!',
    'services.intro_description': 'We are happy to help meet your needs through the best services we provide.',
    'services.no_services': 'No services available at this time.',
    'services.hero_content': 'Bring real transformation to your business through a range of data-driven smart solutions, cutting-edge technology, and deep analytics. We are dedicated to helping you achieve maximum efficiency and potential.',
    'services.intro_content_1': 'Bring real transformation to your business through a range of data-driven smart solutions, cutting-edge technology, and deep analytics.',
    'services.intro_content_2': 'Explore various top solutions using our services!',
    'services.intro_content_3': 'We are happy to help meet your needs through the best services we provide. Do not hesitate to rely on us to provide the right solution for you!',
    'experience.content_1': 'Since its founding in 2006, Wahana Data Utama has carved a long journey as a leading research and data service provider in Indonesia. Our experience in utilizing the latest technologies such as big data analytics, surveys, and the Internet of Things (IoT) allows us to provide relevant and innovative solutions in various sectors. We have collaborated with various industries, from cooperatives and SMEs, agribusiness, to digital advertising, to present fast and accurate cloud-based services. Our experience also includes the application of machine learning in predictive analysis, helping clients face evolving business challenges. With extensive experience in socio-political research, development economics, and marketing management, we remain committed to supporting clients in creating sustainable competitive advantage in the Industrial Revolution 5.0 era.',
    'experience.content_2': 'With a strong commitment to innovation and data accuracy, Wahana Data Utama is ready to be a trusted partner for businesses and organizations in making informed decisions. In an increasingly complex digital era, we continue to innovate with the latest technology to present solutions that are relevant, accurate, and have a real impact.',
    'experience.content_3': 'Client trust is our top priority, and with years of experience and a reliable professional team, we are committed to helping various sectors optimize their business strategies.',
    'experience.content_4': 'With Wahana Data Utama, you don\'t just get data, but also strategic insights that drive long-term growth and success. Let\'s step into the future with smarter, more efficient, and highly competitive strategies!',
    'role.KOMISARIS UTAMA': 'PRESIDENT COMMISSIONER',
    'role.DIREKTUR UTAMA': 'PRESIDENT DIRECTOR',
    'role.DIREKTUR': 'DIRECTOR',
    'services.title.Riset Pasar': 'Market Research',
    'services.desc.Riset Pasar': 'Explore new opportunities and understand market trends with in-depth market research.',
    'services.title.Riset Data': 'Data Research',
    'services.desc.Riset Data': 'Processing primary and secondary data to generate strategic insights.',
    'services.title.Analisis Data': 'Data Analysis',
    'services.desc.Analisis Data': 'Transforming raw data into strategic assets through advanced processing and validation.',
    'services.title.Survei': 'Survey',
    'services.desc.Survei': 'Accurate field data collection with tested scientific methodologies.',
    'services.title.Event Organizer': 'Event Organizer',
    'services.desc.Event Organizer': 'Professional event organization focused on detail and memorable impact.',
    'services.title.Konsultasi IT': 'IT Consulting',
    'services.desc.Konsultasi IT': 'Strategic technology consulting to optimize your business digital infrastructure.',
    'project.info_title': 'Collaboration Information',
    'project.desc_1': 'has established strategic collaboration in various research projects, system development, and data analysis. Through this collaboration, we help our partners achieve operational efficiency and accurate data-driven decision making.',
    'project.desc_2': 'This project involves the implementation of the latest research methodologies and the use of data analysis technology to provide in-depth insights relevant to current industry challenges.',
    'project.quick_info': 'Quick Information',
    'project.category_label': 'Category',
    'project.year_label': 'Year',
    'project.status_label': 'Status',
    'project.status_done': 'Completed',
    'project.other_title': 'Other Collaborations',
    'project.back_to_experience': 'Back to Experience',
    'project.hero_title': 'Project Details',
    'category.Research & Development': 'Research & Development'
  },
  jp: {
    'login.welcome': 'おかえりなさい。',
    'login.subtitle': 'データ管理ポータルにアクセス',
    'login.email_label': 'メール ID',
    'login.password_label': 'セキュリティトークン',
    'login.remember_me': 'このデバイスを信頼する',
    'login.forgot_password': '復旧',
    'login.submit': 'アクセス認証',
    'login.processing': '承認中...',
    'login.footer': 'セキュアポータル © 2026 Wahana Data Utama',
    'login.error': 'メールアドレスまたはパスワードが無効です。',
    'common.loading': '少々お待ちください...',
    'common.intelligence': 'WDU インテリジェンス',
    'common.data_business': 'データは私たちのビジネスです。',
    'common.empowering': '2006年以来、リアルタイムのデータ洞察と高度な分析で意思決定えています。',
    'common.years_exp': '経験年数',
    'common.projects': 'プロジェクト数',
    'common.analytics': '24/7 分析',
    'nav.home': 'ホーム',
    'nav.about': '私たちについて',
    'nav.services': 'サービス',
    'nav.experience': '実績',
    'nav.contact': 'お問い合わせ',
    'nav.download_profile': '会社案内',
    'footer.address': 'オフィス所在地',
    'footer.contact': 'お問い合わせ',
    'footer.social': 'ソーシャルメディア',
    'footer.privacy': 'プライバシー',
    'footer.terms': '利用規約',
    'footer.cookies': 'クッキー',
    'experience.hero_title': '私たちの実績',
    'experience.intro_title': '確かな証拠を通じて信頼を築く。',
    'home.hero_title': '統合データ、スマートソリューション | 最大の結果',
    'home.hero_content': 'リサーチ、データ分析、テクノロジーのニーズをWahana Data Utamaにお任せください。データを価値ある洞察と実用的なソリューションに変え、デジタル時代における競争優位性の獲得を支援します。',
    'home.intro_title': '有能なプロフェッショナルチームに支えられた豊富な経験。',
    'home.stats_projects': '完了したプロジェクト',
    'home.stats_clients': '満足したクライアント',
    'home.stats_efficiency': 'データ効率',
    'home.stats_support': '24時間365日のサポート',
    'home.services_title': '当社のサービス',
    'home.services_subtitle': '統合データソリューション',
    'home.services_content': 'Wahana Data Utamaは、お客様のビジネスや組織がデータを最適に管理、分析、活用できるよう支援することに尽力しています。',
    'home.trust_title': 'クライアントからの信頼',
    'home.trust_subtitle': '18年の経験を活かし、政府機関や民間セクター向けに戦略的なコラボレーションを構築しています。',
    'home.gallery_subtitle': '私たちの活動とコラボレーションのポートレート',
    'home.gallery_quote': '「データの正確さは私たちの約束であり、コラボレーションは私たちの強みです。」',
    'about.mission_title': 'あなたへの私たちの使命',
    'about.mission_desc': 'お客様のビジネスの進歩のために、誠実さと幅広い影響力を持つデータソリューションを提供することに尽力しています。',
    'about.vision_label': 'ビジョン',
    'about.vision_text': 'グローバルなリサーチ・調査データ提供会社になること。',
    'about.mission_label': '使命',
    'about.mission_1': '科学的規則に従って信頼できるリサーチ、調査、研究を実施し、正確、精密、信頼性の高いデータを生成すること。',
    'about.mission_2': '正確、精密、信頼性の高い活動を組織すること。',
    'about.mission_3': '革新、ソリューション、アイデアに満ちたクリエイティブな企業であること。',
    'about.pillar_1_title': '科学的信頼性',
    'about.pillar_1_desc': '科学的規則に従って信頼できるリサーチ、調査、研究を実施する。',
    'about.pillar_2_title': '運用上の精度',
    'about.pillar_2_desc': '正確、精密、信頼性の高い活動を組織する。',
    'about.pillar_3_title': '革新的なイノベーション',
    'about.pillar_3_desc': '革新、ソリューション、アイデアに満ちたクリエイティブな企業であること。',
    'about.leadership_label': '私たちのリーダーシップ',
    'about.directors_title': '取締役会',
    'contact.hero_title': 'お問い合わせ',
    'contact.intro_title': '一緒に素晴らしいことを始めましょう。',
    'contact.hero_label': 'エディトリアル・インテリジェンス',
    'contact.address_label': 'オフィスの住所',
    'contact.email_label': 'メール',
    'contact.phone_label': '電話',
    'contact.form_title': 'メッセージを送る',
    'contact.success_title': 'ありがとうございます！',
    'contact.success_message': 'メッセージは正常に送信されました。間もなくご連絡いたします。',
    'contact.send_again': '別のメッセージを送る',
    'contact.full_name': 'フルネーム',
    'contact.business_email': 'ビジネスメール',
    'contact.phone_number': '電話番号',
    'contact.message': 'メッセージ',
    'contact.message_placeholder': '今日はどのようなご用件でしょうか？',
    'contact.sending': '送信中...',
    'contact.send_button': '今すぐメッセージを送る',
    'contact.privacy_note': 'あなたのデータは当社のプライバシーポリシーに従って安全に保管されます。',
    'contact.hero_description': '私たちはあなたのビジョンに耳を傾け、的確なテクノロジーソリューションを提供するためにここにいます。初回のご相談やサービスに関するお問い合わせなど、お気軽にご連絡ください。',
    'home.hero_click': 'クリックしてビジョンを見る',
    'home.loading_services': 'サービスを読み込み中...',
    'home.no_services': '利用可能なサービスはありません。',
    'home.solution_title': 'データソリューション',
    'home.director_title': '代表取締役',
    'about.hero_title': 'Precision Intelligence',
    'about.data_business_desc': '2006年以来、グローバル企業を支援しています。',
    'about.pro_title': '経験豊富なプロフェッショナルの最前線',
    'contact.intro_description': '当社のエキスパートチームは、デジタルトランスフォーメーションやスマートデータ管理に関するあらゆるご質問に迅速に対応いたします。',
    'experience.track_record': '私たちの実績',
    'experience.headquarter': 'WDU 本部',
    'experience.quality_assured': '品質保証',
    'experience.data_accurate': '戦略的決定のための正確なデータ。',
    'experience.milestones_title': 'マイルストーン',
    'experience.milestones_subtitle': '戦略的パートナーと国内コラボレーション',
    'experience.partners_count': 'パートナー',
    'experience.syncing': 'パートナーデータを同期中...',
    'services.intro_subtitle': '当社のサービス',
    'services.intro_title': '当社のサービスを利用して、さまざまな優れたソリューションを探索してください。',
    'services.intro_description': '提供する最高のサービスを通じて、お客様のニーズにお応えできることを嬉しく思います。',
    'services.no_services': '現在、利用可能なサービスはありません。',
    'services.data_business_desc': 'データは単なる数字ではなく、最高のソリューションを作成するための基盤です。専門知識とテクノロジーを活用して、成長と革新を促進する洞察をもたらします。',
    'services.title.Big Data Analytics': 'ビッグデータ分析',
    'services.desc.Big Data Analytics': '複雑なデータをビジネス成長のための戦略的洞察に変換します。',
    'services.title.Digital Survey': 'デジタル調査',
    'services.desc.Digital Survey': '最先端のデジタル手法による迅速かつ正確なデータ収集。',
    'services.title.IoT Solutions': 'IoTソリューション',
    'services.desc.IoT Solutions': 'デバイスとデータを接続し、よりスマートな運用効率を実現します。',
    'services.title.Strategic Consulting': '戦略コンサルティング',
    'services.desc.Strategic Consulting': 'ビジネスの課題と将来の機会をナビゲートするための専門家によるガイダンス。',
    'services.title.GIS Mapping': 'GISマッピング',
    'services.desc.GIS Mapping': '精密な計画と空間分析のための地理データ視覚化。',
    'services.title.Research & Development': 'リサーチ＆デベロップメント',
    'services.desc.Research & Development': '詳細な研究とテストに裏打ちされた継続的なイノベーション。',
    'home.intro_content': 'Wahana Data Utamaは、2006年に社会政治、経済、マーケティング、農業などに焦点を当てたリサーチおよび調査会社として設立されました。グローバルなリサーチデータプロバイダーになるというビジョンのもと、WDUは10年以上の経験を持つプロフェッショナルチームによって支えられています。ボゴールを拠点とし、リサーチからイベントの企画運営まで、さまざまなコンサルティングプロジェクトを処理するために、さまざまな政府機関や民間機関の信頼を得てきました。',
    'about.intro_content': 'Wahana Data Utamaは2006年に設立され、インドネシアのリサーチおよびデータサービス提供におけるリーディングカンパニーへと成長しました。「Data Is Our Business」というビジョンのもと、ビッグデータ分析、調査の実施、モノのインターネット（IoT）などの最新技術を活用し、インダストリアル・レボリューション5.0時代において、適切でグローバルに競争力のあるサービスを提供することにより、リサーチベースのデータソリューションのパイオニアになることに尽力しています。<br/><br/>ボゴールのGraha Nurul Mentengに拠点を置き、社会政治リサーチ、環境研究、開発経済、マーケティング管理におけるデジタルイノベーションを統合し、協同組合や中小企業、アグリビジネス、デジタル広告など、さまざまなニーズに対応する高速で正確なクラウドベースのソリューションを提供しています。予測分析のための機械学習などの最先端技術を適用することで、現代のビジネス課題に直面し、持続可能な競争優位性を構築するクライアントをサポートしています。',
    'about.pro_content': '10年以上の専門知識を持つ経験豊富なプロフェッショナルによって設立された私たちは、現代のテクノロジーに基づいた方法論的アプローチを使用して、計画、実行、監督から評価まで、あらゆる運用面で強固な会社の基盤を構築しています。トレーニングを受け、認定された当社の専門家は、リサーチや高度な分析ソフトウェアの使用を含む、デジタルベースの教育とトレーニングを通じて、継続的に能力を向上させています。<br/><br/>政府機関や民間機関の戦略的パートナーとして、グローバル市場動向のリサーチ、テクノロジーベースの専門トレーニング、デジタルプラットフォームによってサポートされるイベント運営など、さまざまな複雑で多次元的なコンサルティングプロジェクトを完了することで、その能力を証明してきました。<br/><br/>グローバルな課題、デジタルトランスフォーメーション、経済のレジリエンスに直面するための持続可能なソリューションの統合により、データを戦略的資産として活用し、国内および国際的な発展をサポートしています。2025年も、未来志向のデータ駆動型エコシステムにおいてイノベーションと重要な変化をもたらす、信頼できるパートナーであり続けることに尽力しています。',
    'role.KOMISARIS UTAMA': '会長',
    'role.DIREKTUR UTAMA': '代表取締役',
    'role.DIREKTUR': '取締役',
    'services.title.Riset Pasar': '市場調査',
    'services.desc.Riset Pasar': '詳細な市場調査により、新しい機会を探索し、市場動向を把握します。',
    'services.title.Riset Data': 'データ調査',
    'services.desc.Riset Data': '一次データおよび二次データを処理して、戦略的な洞察を生成します。',
    'services.title.Analisis Data': 'データ分析',
    'services.desc.Analisis Data': '高度な処理と検証を通じて、生データを戦略的資産に変換します。',
    'services.title.Survei': '調査',
    'services.desc.Survei': 'テスト済みの科学的手法による正確なフィールドデータ収集。',
    'services.title.Event Organizer': 'イベント企画',
    'services.desc.Event Organizer': '細部と記憶に残るインパクトに焦点を当てたプロフェッショナルなイベント組織。',
    'services.title.Konsultasi IT': 'ITコンサルティング',
    'services.desc.Konsultasi IT': 'ビジネスのデジタルインフラストラクチャを最適化するための戦略的テクノロジーコンサルティング。'
  },
  zh: {
    'login.welcome': '欢迎回来。',
    'login.subtitle': '访问您的数据管理门户',
    'login.email_label': '电子邮件身份',
    'login.password_label': '安全令牌',
    'login.remember_me': '信任此设备',
    'login.forgot_password': '找回密码',
    'login.submit': '身份验证',
    'login.processing': '正在授权...',
    'login.footer': '安全门户 © 2026 Wahana Data Utama',
    'login.error': '电子邮件或密码无效。',
    'common.loading': '请稍等...',
    'common.intelligence': 'WDU 智能',
    'common.data_business': '数据是我们的核心。',
    'common.empowering': '自 2006 年以来，通过实时数据洞察和高级分析为决策者提供支持。',
    'common.years_exp': '经验年限',
    'common.projects': '完成项目',
    'common.analytics': '24/7 全天候分析',
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务项目',
    'nav.experience': '项目经验',
    'nav.contact': '联系我们',
    'nav.download_profile': '公司简介',
    'footer.address': '办公地址',
    'footer.contact': '联系我们',
    'footer.social': '社交媒体',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.cookies': 'Cookie 政策',
    'experience.hero_title': '我们的业绩',
    'experience.intro_title': '通过真实证据建立信任。',
    'home.hero_title': '统一数据，智能解决方案 | 最大的成效',
    'home.hero_content': '将您的研究、数据分析和技术需求委托给 Wahana Data Utama。我们将数据转化为宝贵的洞察和实用的解决方案，帮助您在数字时代获得竞争优势。',
    'home.intro_title': '丰富的经验，由称职的专业团队支持。',
    'home.stats_projects': '已完成项目',
    'home.stats_clients': '满意客户',
    'home.stats_efficiency': '数据效率',
    'home.stats_support': '24/7 支持',
    'home.services_title': '我们的服务',
    'home.services_subtitle': '集成数据解决方案',
    'home.services_content': 'Wahana Data Utama 致力于帮助您的企业和组织优化管理、分析和利用数据。',
    'home.trust_title': '客户对我们的信任',
    'home.trust_subtitle': '凭借 18 年的经验，我们为政府机构和私营部门建立了战略合作。',
    'home.gallery_subtitle': '我们的活动与合作肖像',
    'home.gallery_quote': '“数据准确性是我们的承诺，合作是我们的力量。”',
    'about.mission_title': '我们对您的使命',
    'about.mission_desc': '致力于为您的业务进步提供具有诚信和广泛影响的数据解决方案。',
    'about.vision_label': '愿景',
    'about.vision_text': '成为全球研究/调查数据提供商公司。',
    'about.mission_label': '使命',
    'about.mission_1': '根据科学规则进行可靠的研究、调查和研究，以产生准确、精密和可靠的数据。',
    'about.mission_2': '准确、精密、可靠地组织活动。',
    'about.mission_3': '成为一家充满创新、解决方案和想法的创意公司。',
    'about.pillar_1_title': '科学信誉',
    'about.pillar_1_desc': '根据科学规则进行可靠的研究、调查和研究。',
    'about.pillar_2_title': '运营精度',
    'about.pillar_2_desc': '准确、精密、可靠地组织活动。',
    'about.pillar_3_title': '创意创新',
    'about.pillar_3_desc': '成为一家充满创新、解决方案和想法的创意公司。',
    'about.leadership_label': '我们的领导层',
    'about.directors_title': '董事会',
    'contact.hero_title': '联系我们',
    'contact.intro_title': '让我们一起开启伟大的事业。',
    'contact.hero_label': '编辑情报',
    'contact.address_label': '办公地址',
    'contact.email_label': '电子邮件',
    'contact.phone_label': '电话',
    'contact.form_title': '发送消息',
    'contact.success_title': '谢谢！',
    'contact.success_message': '您的消息已成功发送。我们将尽快与您联系。',
    'contact.send_again': '再次发送消息',
    'contact.full_name': '全名',
    'contact.business_email': '业务邮箱',
    'contact.phone_number': '电话号码',
    'contact.message': '消息',
    'contact.message_placeholder': '我们今天能为您提供什么帮助？',
    'contact.sending': '发送中...',
    'contact.send_button': '立即发送消息',
    'contact.privacy_note': '您的数据将根据我们的隐私政策安全存储。',
    'contact.hero_description': '我们在这里倾听您的愿景，并提供精准的技术解决方案。欢迎联系我们进行初步咨询，或询问有关我们服务的信息。',
    'home.hero_click': '点击查看我们的愿景',
    'home.loading_services': '正在加载服务...',
    'home.no_services': '目前没有可用服务。',
    'home.solution_title': '数据解决方案',
    'home.director_title': '总裁',
    'about.hero_title': 'Precision Intelligence',
    'about.data_business_desc': '自2006年以来为全球企业赋能。',
    'about.pro_title': '经验丰富的专业人士前沿',
    'contact.intro_description': '我们的专家团队随时准备为您解答有关数字化转型和智能数据管理的任何问题。',
    'experience.track_record': '我们的业绩记录',
    'experience.headquarter': 'WDU 总部',
    'experience.quality_assured': '质量保证',
    'experience.data_accurate': '为战略决策提供准确数据。',
    'experience.milestones_title': '里程碑',
    'experience.milestones_subtitle': '战略合作伙伴与国家级合作',
    'experience.partners_count': '合作伙伴',
    'experience.syncing': '正在同步合作伙伴数据...',
    'services.intro_subtitle': '我们的服务',
    'services.intro_title': '使用我们的服务探索各种顶级解决方案！',
    'services.intro_description': '我们很高兴通过我们提供的最佳服务满足您的需求。',
    'services.no_services': '目前没有可用服务。',
    'services.data_business_desc': '数据对我们来说不仅仅是数字，更是创造最佳解决方案的基石。凭借专业知识和技术，我们带来推动增长和创新的洞察力。',
    'home.intro_content': 'Wahana Data Utama 成立于 2006 年，是一家专注于社会政治、经济、市场营销、农业等领域的研究和调查公司。秉承成为全球研究数据提供商的愿景，WDU 拥有一支拥有 10 年以上经验的专业团队。总部位于茂物，我们赢得了各种政府和私营机构的信任，处理从研究到活动组织的各种咨询项目。',
    'about.intro_content': 'Wahana Data Utama 成立于 2006 年，现已成长为印度尼西亚提供研究和数据服务的领先公司，其愿景是“数据是我们的事业”。我们致力于通过利用大数据分析、调查执行和物联网 (IoT) 等最新技术，成为基于研究的数据解决方案的先驱，在工业 5.0 时代提供相关且具有全球竞争力的服务。<br/><br/>总部位于茂物 Graha Nurul Menteng，我们将数字创新整合到社会政治研究、环境研究、发展经济学到营销管理中，并为各种需求提供快速准确的基于云的解决方案，包括合作社和中小企业、农业综合企业和数字广告。通过应用预测分析的机器学习等尖端技术，我们支持客户应对现代商业挑战并创造可持续的竞争优势。',
    'about.pro_content': '由拥有十多年专业经验的资深人士创立，我们使用基于现代技术的微型方法论，在规划、执行、监督到评估的每个运营方面建立稳固的公司基础。我们经过培训和认证的专家通过基于数字的教育和培训（包括研究和高级分析软件的使用）不断提高其能力。<br/><br/>作为政府和私营机构的战略合作伙伴，我们通过完成各种复杂和多维咨询项目证明了我们的能力，涵盖全球市场趋势研究、基于技术的专业培训以及由数字平台支持的活动组织。<br/><br/>通过整合可持续解决方案以应对全球挑战、数字化转型和经济复苏，我们将数据作为战略资产来支持国家和国际发展。到 2025 年，我们将继续致力于成为值得信赖的合作伙伴，在面向未来的数据驱动生态系统中带来创新和重大变革。',
    'role.KOMISARIS UTAMA': '董事长',
    'role.DIREKTUR UTAMA': '总裁',
    'role.DIREKTUR': '董事',
    'services.title.Riset Pasar': '市场研究',
    'services.desc.Riset Pasar': '通过深入的市场研究探索新机遇并了解市场趋势。',
    'services.title.Riset Data': '数据研究',
    'services.desc.Riset Data': '处理一手和二手数据以产生战略见解。',
    'services.title.Analisis Data': '数据分析',
    'services.desc.Analisis Data': '通过先进的处理和验证将原始数据转化为战略资产。',
    'services.title.Survei': '调查',
    'services.desc.Survei': '使用经过测试的科学方法进行准确的现场数据收集。',
    'services.title.Event Organizer': '活动策划',
    'services.desc.Event Organizer': '专注于细节和难忘影响的专业活动组织。',
    'services.title.Konsultasi IT': 'IT咨询',
    'services.desc.Konsultasi IT': '战略技术咨询，优化您的企业数字化基础设施。'
  },
  es: {
    'login.welcome': 'Bienvenido de nuevo.',
    'login.subtitle': 'Acceda a su portal de gestión de datos',
    'login.email_label': 'Identidad de correo',
    'login.password_label': 'Token de seguridad',
    'login.remember_me': 'Confiar en este dispositivo',
    'login.forgot_password': 'Recuperación',
    'login.submit': 'Autenticar acceso',
    'login.processing': 'Autorizando...',
    'login.footer': 'Portal Seguro © 2026 Wahana Data Utama',
    'login.error': 'Correo o contraseña no válidos.',
    'common.loading': 'Un momento, por favor...',
    'common.intelligence': 'WDU Intelligence',
    'common.data_business': 'LOS DATOS SON NUESTRO NEGOCIO.',
    'common.empowering': 'Empoderando a los tomadores de decisiones con conocimientos de datos en tiempo real y análisis avanzados desde 2006.',
    'common.years_exp': 'Años de Exp',
    'common.projects': 'Proyectos',
    'common.analytics': 'Análisis 24/7',
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.services': 'Servicios',
    'nav.experience': 'Experiencia',
    'nav.contact': 'Contacto',
    'nav.download_profile': 'Perfil de Empresa',
    'footer.address': 'Dirección de la oficina',
    'footer.contact': 'Contáctenos',
    'footer.social': 'Redes Sociales',
    'footer.privacy': 'Privacidad',
    'footer.terms': 'Términos',
    'footer.cookies': 'Cookies',
    'contact.hero_title': 'CONTÁCTENOS',
    'contact.intro_title': 'Comencemos algo grande juntos.',
    'contact.hero_label': 'Inteligencia Editorial',
    'contact.address_label': 'Dirección de la oficina',
    'contact.email_label': 'Correo electrónico',
    'contact.phone_label': 'Teléfono',
    'contact.form_title': 'Enviar mensaje',
    'contact.success_title': '¡Gracias!',
    'contact.success_message': 'Su mensaje ha sido enviado con éxito. Nos pondremos en contacto con usted pronto.',
    'contact.send_again': 'Enviar otro mensaje',
    'contact.full_name': 'Nombre completo',
    'contact.business_email': 'Correo electrónico comercial',
    'contact.phone_number': 'Número de teléfono',
    'contact.message': 'Mensaje',
    'contact.message_placeholder': '¿Cómo podemos ayudar a su negocio hoy?',
    'contact.sending': 'Enviando...',
    'contact.send_button': 'Enviar mensaje ahora',
    'contact.privacy_note': 'Sus datos se almacenan de forma segura de acuerdo con nuestra política de privacidad.',
    'contact.hero_description': 'Estamos aquí para escuchar su visión y brindar soluciones tecnológicas que den en el blanco. No dude en contactarnos para una consulta inicial o simplemente para preguntar sobre nuestros servicios.',
    'contact.intro_description': 'Nuestro equipo de expertos está listo para brindar una respuesta rápida a cualquiera de sus preguntas sobre transformación digital y gestión inteligente de datos.',
    'experience.hero_title': 'NUESTRA EXPERIENCIA',
    'experience.intro_title': 'Construyendo confianza a través de evidencia real.',
    'home.hero_title': 'Datos Unificados, Soluciones Inteligentes | Resultados Máximos',
    'home.hero_content': 'Confíe sus necesidades de investigación, análisis de datos y tecnología a Wahana Data Utama. Transformamos los datos en conocimientos valiosos y soluciones prácticas que le ayudan a obtener una ventaja competitiva en la era digital.',
    'home.intro_title': 'Amplia experiencia respaldada por un equipo profesional competente.',
    'home.stats_projects': 'Proyectos Completados',
    'home.stats_clients': 'Clientes Satisfechos',
    'home.stats_efficiency': 'Eficiencia de Datos',
    'home.stats_support': 'Soporte 24/7',
    'home.services_title': 'Nuestros Servicios',
    'home.services_subtitle': 'Soluciones de Datos Integradas',
    'home.services_content': 'Wahana Data Utama se compromete a ayudar a su empresa y organización a gestionar, analizar y utilizar los datos de manera óptima.',
    'home.trust_title': 'Confianza del Cliente en Nosotros',
    'home.trust_subtitle': 'Con 18 años de experiencia, construimos colaboraciones estratégicas para organizaciones gubernamentales y el sector privado.',
    'home.gallery_subtitle': 'Retratos de nuestras actividades y colaboraciones',
    'home.gallery_quote': '"La precisión de los datos es nuestra promesa, la colaboración es nuestra fuerza."',
    'about.mission_title': 'Nuestra Misión para Usted',
    'about.mission_desc': 'Comprometidos a proporcionar soluciones de datos con integridad y amplio impacto para el progreso de su negocio.',
    'about.vision_label': 'Visión',
    'about.vision_text': 'Ser una empresa proveedora de datos de investigación/encuestas global.',
    'about.mission_label': 'Misión',
    'about.mission_1': 'Realizar investigaciones, encuestas y estudios creíbles de acuerdo con las reglas científicas para producir datos exactos, precisos y confiables.',
    'about.mission_2': 'Organizar una actividad de forma exacta, precisa y fiable.',
    'about.mission_3': 'Ser una empresa creativa llena de innovación, soluciones e ideas.',
    'about.pillar_1_title': 'Credibilidad Científica',
    'about.pillar_1_desc': 'Realizar investigaciones, encuestas y estudios creíbles de acuerdo con las reglas científicas.',
    'about.pillar_2_title': 'Precisión Operativa',
    'about.pillar_2_desc': 'Organizar una actividad de forma exacta, precisa y fiable.',
    'about.pillar_3_title': 'Innovación Creativa',
    'about.pillar_3_desc': 'Ser una empresa creativa llena de innovación, soluciones e ideas.',
    'home.hero_click': 'Haga clic para explorar nuestra visión',
    'home.loading_services': 'Cargando servicios...',
    'home.no_services': 'No hay servicios disponibles.',
    'home.solution_title': 'Soluciones de Datos',
    'home.director_title': 'Director General',
    'about.hero_title': 'Precision Intelligence',
    'about.data_business_desc': 'Empoderando a empresas globales desde 2006.',
    'about.pro_title': 'La vanguardia de profesionales experimentados',
    'about.leadership_label': 'Nuestro Liderazgo',
    'about.directors_title': 'Junta Directiva',
    'experience.track_record': 'NUESTRO TRAYECTORIA',
    'experience.headquarter': 'Sede de WDU',
    'experience.quality_assured': 'Calidad Garantizada',
    'experience.data_accurate': 'Datos precisos para decisiones estratégicas.',
    'experience.milestones_title': 'Hitos',
    'experience.milestones_subtitle': 'Socios Estratégicos y Colaboración Nacional',
    'experience.partners_count': 'Socios',
    'experience.syncing': 'Sincronizando datos de socios...',
    'services.intro_subtitle': 'Nuestros Servicios',
    'services.intro_title': '¡Explore diversas soluciones de primer nivel utilizando nuestros servicios!',
    'services.intro_description': 'Estaremos encantados de ayudarle a satisfacer sus necesidades a través de los mejores servicios que brindamos.',
    'services.no_services': 'No hay servicios disponibles en este momento.',
    'services.data_business_desc': 'Los datos no son solo números para nosotros, sino la base para crear las mejores soluciones. Con experiencia y tecnología, aportamos conocimientos que impulsan el crecimiento y la innovación.',
    'services.title.Big Data Analytics': 'Analítica de Big Data',
    'services.desc.Big Data Analytics': 'Transformando datos complejos en conocimientos estratégicos para el crecimiento de su negocio.',
    'services.title.Digital Survey': 'Encuesta Digital',
    'services.desc.Digital Survey': 'Recopilación de datos rápida y precisa con metodologías digitales de vanguardia.',
    'services.title.IoT Solutions': 'Soluciones IoT',
    'services.desc.IoT Solutions': 'Conectando dispositivos y datos para una eficiencia operativa más inteligente.',
    'services.title.Strategic Consulting': 'Consultoría Estratégica',
    'services.desc.Strategic Consulting': 'Guía experta para navegar los desafíos comerciales y las oportunidades futuras.',
    'services.title.GIS Mapping': 'Mapeo GIS',
    'services.desc.GIS Mapping': 'Visualización de datos geográficos para una planificación de precisión y análisis espacial.',
    'services.title.Research & Development': 'Investigación y Desarrollo',
    'services.desc.Research & Development': 'Innovación continua impulsada por una investigación y pruebas exhaustivas.',
    'home.intro_content': 'Wahana Data Utama fue fundada en 2006 como una empresa de investigación y encuestas centrada en los campos socio-político, económico, de marketing, agrícola y otros. Con la visión de convertirse en un proveedor global de datos de investigación, WDU cuenta con el respaldo de un equipo profesional con más de 10 años de experiencia. Con sede en Bogor, nos hemos ganado la confianza de diversas agencias gubernamentales y privadas para manejar diversos proyectos de consultoría, desde investigación hasta organización de eventos.',
    'about.intro_content': 'Wahana Data Utama fue fundada en 2006 y ha crecido hasta convertirse en una empresa líder en la prestación de servicios de investigación y datos en Indonesia con la visión "Data Is Our Business". Estamos comprometidos a ser pioneros en soluciones de datos basadas en la investigación mediante el uso de las últimas tecnologías, como el análisis de big data, la ejecución de encuestas y el Internet de las cosas (IoT), para proporcionar servicios relevantes y competitivos a nivel mundial en la era de la Revolución Industrial 5.0.<br/><br/>Con sede en Graha Nurul Menteng, Bogor, integramos la innovación digital en la investigación socio-política, estudios ambientales, economía del desarrollo, hasta la gestión de marketing, y ofrecemos soluciones rápidas y precisas basadas en la nube para diversas necesidades, incluyendo cooperativas y pymes, agronegocios y publicidad digital. A través de la aplicación de tecnologías de vanguardia como el aprendizaje automático para el análisis predictivo, apoyamos a los clientes a enfrentar los desafíos comerciales modernos y crear ventajas competitivas sostenibles.',
    'about.pro_content': 'Fundada por profesionales experimentados con más de una década de especialización, construimos una base sólida de la empresa en cada aspecto operativo, desde la planificación, ejecución, supervisión hasta la evaluación, utilizando enfoques metodológicos basados en tecnología moderna. Nuestros expertos capacitados y certificados mejoran continuamente su competencia a través de educación y capacitación digital, incluyendo la investigación y el uso de software analítico avanzado.<br/><br/>Como socio estratégico de agencias gubernamentales y privadas, hemos demostrado nuestras capacidades al completar diversos proyectos de consultoría complejos y multidimensionales, que abarcan la investigación de tendencias del mercado global, capacitación profesional basada en tecnología, hasta la organización de eventos respaldada por plataformas digitales.<br/><br/>Con la integración de soluciones sostenibles para enfrentar desafíos globales, la transformación digital y la resiliencia económica, utilizamos los datos como un activo estratégico para apoyar el desarrollo nacional e internacional. En 2025, seguimos comprometidos a ser un socio de confianza que brinde innovación y cambios significativos en un ecosistema orientado al futuro y basado en datos.',
    'role.KOMISARIS UTAMA': 'Presidente del Consejo',
    'role.DIREKTUR UTAMA': 'Director General',
    'role.DIREKTUR': 'Director',
    'services.title.Riset Pasar': 'Investigación de Mercado',
    'services.desc.Riset Pasar': 'Explore nuevas oportunidades y comprenda las tendencias del mercado con una investigación de mercado profunda.',
    'services.title.Riset Data': 'Investigación de Datos',
    'services.desc.Riset Data': 'Procesamiento de datos primarios y secundarios para generar conocimientos estratégicos.',
    'services.title.Analisis Data': 'Análisis de Datos',
    'services.desc.Analisis Data': 'Transformación de datos brutos en activos estratégicos a través de un procesamiento y validación avanzados.',
    'services.title.Survei': 'Encuesta',
    'services.desc.Survei': 'Recopilación precisa de datos de campo con metodologías científicas probadas.',
    'services.title.Event Organizer': 'Organizador de Eventos',
    'services.desc.Event Organizer': 'Organización de eventos profesionales enfocada en el detalle y un impacto memorable.',
    'services.title.Konsultasi IT': 'Consultoría de TI',
    'services.desc.Konsultasi IT': 'Consultoría tecnológica estratégica para optimizar la infraestructura digital de su negocio.'
  },
  ar: {
    'login.welcome': 'مرحباً بعودتك.',
    'login.subtitle': 'الوصول إلى بوابة إدارة البيانات الخاصة بك',
    'login.email_label': 'هوية البريد الإلكتروني',
    'login.password_label': 'رمز الأمان',
    'login.remember_me': 'الوثوق بهذا الجهاز',
    'login.forgot_password': 'استعادة الحساب',
    'login.submit': 'مصادقة الدخول',
    'login.processing': 'جاري التفويض...',
    'login.footer': 'البوابة الآمنة © 2026 Wahana Data Utama',
    'login.error': 'البريد الإلكتروني أو كلمة المرور غير صالحة.',
    'common.loading': 'يرجى الانتظار لحظة...',
    'common.intelligence': 'WDU للذكاء',
    'common.data_business': 'البيانات هي عملنا.',
    'common.empowering': 'تمكين صناع القرار من خلال رؤى البيانات في الوقت الفعلي والتحليلات المتقدمة منذ عام 2006.',
    'common.years_exp': 'سنوات الخبرة',
    'common.projects': 'المشاريع',
    'common.analytics': 'تحليلات 24/7',
    'nav.home': 'الرئيسية',
    'nav.about': 'من نحن',
    'nav.services': 'خدماتنا',
    'nav.experience': 'خبراتنا',
    'nav.contact': 'اتصل بنا',
    'nav.download_profile': 'ملف الشركة',
    'footer.address': 'عنوان المكتب',
    'footer.contact': 'اتصل بنا',
    'footer.social': 'وسائل التواصل',
    'footer.privacy': 'الخصوصية',
    'footer.terms': 'الشروط',
    'footer.cookies': 'الكوكيز',
    'contact.hero_title': 'اتصل بنا',
    'contact.intro_title': 'لنبدأ شيئاً عظيماً معاً.',
    'contact.hero_label': 'الذكاء التحريري',
    'contact.address_label': 'عنوان المكتب',
    'contact.email_label': 'البريد الإلكترoni',
    'contact.phone_label': 'الهاتف',
    'contact.form_title': 'إرسال رسالة',
    'contact.success_title': 'شكراً لك!',
    'contact.success_message': 'تم إرسال رسالتك بنجاح. سنتصل بك قريباً.',
    'contact.send_again': 'إرسال رسالة أخرى',
    'contact.full_name': 'الاسم الكامل',
    'contact.business_email': 'البريد الإلكتروني للعمل',
    'contact.phone_number': 'رقم الهاتف',
    'contact.message': 'الرسالة',
    'contact.message_placeholder': 'كيف يمكننا مساعدة عملك اليوم؟',
    'contact.sending': 'جاري الإرسال...',
    'contact.send_button': 'أرسل الرسالة الآن',
    'contact.privacy_note': 'يتم تخزين بياناتك بشكل آمن وفقاً لسياسة الخصوصية الخاصة بنا.',
    'contact.hero_description': 'نحن هنا للاستماع إلى رؤيتك وتقديم الحلول التقنية المناسبة تماماً. لا تتردد في الاتصال بنا للحصول على استشارة أولية أو مجرد السؤال عن خدماتنا.',
    'contact.intro_description': 'فريق الخبراء لدينا جاهز لتقديم استجابة سريعة لأي من أسئلتك بخصوص التحول الرقمي وإدارة البيانات الذكية.',
    'experience.hero_title': 'خبرتنا',
    'experience.intro_title': 'بناء الثقة من خلال الأدلة الحقيقية.',
    'home.hero_title': 'بيانات موحدة، حلول ذكية | أقصى قدر من النتائج',
    'home.hero_content': 'عهد باحتياجاتك في البحث وتحليل البيانات والتكنولوجيا إلى Wahana Data Utama. نحن نحول البيانات إلى رؤى قيمة وحلول عملية تساعدك على اكتساب ميزة تنافسية في العصر الرقمي.',
    'home.intro_title': 'خبرة واسعة مدعومة بفريق مهني كفء.',
    'home.stats_projects': 'مشاريع مكتملة',
    'home.stats_clients': 'عملاء راضون',
    'home.stats_efficiency': 'كفاءة البيانات',
    'home.stats_support': 'دعم على مدار الساعة',
    'home.services_title': 'خدماتنا',
    'home.services_subtitle': 'حلol بيانات متكاملة',
    'home.services_content': 'تلتزم Wahana Data Utama بمساعدة عملك ومؤسستك على إدارة البيانات وتحليلها واستخدامها على النحو الأمثل.',
    'home.trust_title': 'ثقة العملاء بنا',
    'home.trust_subtitle': 'مع 18 عاماً من الخبرة، نبني تعاونات استراتيجية للمؤسسات الحكومية والقطاع الخاص.',
    'home.gallery_subtitle': 'صور لأنشطتنا وتعاوناتنا',
    'home.gallery_quote': '"دقة البيانات هي وعدنا، والتعاون هو قوتنا."',
    'about.mission_title': 'مهمتنا تجاهك',
    'about.mission_desc': 'ملتزمون بتقديم حلول بيانات بنزاهة وتأثير واسع لتقدم عملك.',
    'about.vision_label': 'الرؤية',
    'about.vision_text': 'أن نكون شركة عالمية لتوفير بيانات البحوث/المسوح.',
    'about.mission_label': 'المهمة',
    'about.mission_1': 'إجراء بحوث ومسوحات ودراسات موثوقة وفقاً للقواعد العلمية لإنتاج بيانات دقيقة وموثوقة.',
    'about.mission_2': 'تنظيم نشاط بدقة وإحكام وموثوقية.',
    'about.mission_3': 'أن نكون شركة إبداعية مليئة بالابتكار والحلول والأفكار.',
    'about.pillar_1_title': 'المصداقية العلمية',
    'about.pillar_1_desc': 'إجراء بحوث ومسوحات ودراسات موثوقة وفقاً للقواعد العلمية.',
    'about.pillar_2_title': 'الدقة التشغيلية',
    'about.pillar_2_desc': 'تنظيم نشاط بدقة وإحكام وموثوقية.',
    'about.pillar_3_title': 'الابتكار الإبداعي',
    'about.pillar_3_desc': 'أن نكون شركة إبداعية مليئة بالابتكار والحلول والأفكار.',
    'about.leadership_label': 'قيادتنا',
    'about.directors_title': 'مجلس الإدارة',
    'experience.track_record': 'سجل تتبعنا',
    'experience.headquarter': 'مقر WDU الرئيسي',
    'experience.quality_assured': 'جودة مضمونة',
    'experience.data_accurate': 'بيانات دقيقة للقرارات الاستراتيجية.',
    'experience.milestones_title': 'الإنجازات',
    'experience.milestones_subtitle': 'الشركاء الاستراتيجيون والتعاون الوطني',
    'experience.partners_count': 'شركاء',
    'experience.syncing': 'جاري مزامنة بيانات الشركاء...',
    'services.intro_subtitle': 'خدماتنا',
    'services.intro_title': 'استكشف الحلول المتميزة المتنوعة باستخدام خدماتنا!',
    'services.intro_description': 'يسعدنا المساعدة في تلبية احتياجاتك من خلال أفضل الخدمات التي نقدمها.',
    'services.no_services': 'لا توجد خدمات متاحة في الوقت الحالي.',
    'services.data_business_desc': 'البيانات ليست مجرد أرقام بالنسبة لنا، بل هي الأساس لإنشاء أفضل الحلول. بفضل الخبرة والتكنولوجيا، نقدم رؤى تدفع النمو والابتكار.',
    'services.title.Big Data Analytics': 'تحليلات البيانات الضخمة',
    'services.desc.Big Data Analytics': 'تحويل البيانات المعقدة إلى رؤى استراتيجية لنمو عملك.',
    'services.title.Digital Survey': 'المسح الرقمي',
    'services.desc.Digital Survey': 'جمع بيانات سريع ودقيق بأحدث المنهجيات الرقمية.',
    'services.title.IoT Solutions': 'حلول إنترنت الأشياء',
    'services.desc.IoT Solutions': 'ربط الأجهزة والبيانات لكفاءة تشغيلية أكثر ذكاءً.',
    'services.title.Strategic Consulting': 'الاستشارات الاستراتيجية',
    'services.desc.Strategic Consulting': 'توجيه الخبراء للتنقل في تحديات الأعمال والفرص المستقبلية.',
    'services.title.GIS Mapping': 'رسم خرائط نظم المعلومات الجغرافية',
    'services.desc.GIS Mapping': 'تصوير البيانات الجغرافية للتخطيط الدقيق والتحليل المكاني.',
    'services.title.Research & Development': 'البحث والتطوير',
    'services.desc.Research & Development': 'ابتكار مستمر مدفوع بالأبحاث والاختبارات المتعمقة.',
    'home.intro_content': 'تأسست Wahana Data Utama في عام 2006 كشركة أبحاث واستطلاعات تركز على المجالات الاجتماعية والسياسية والاقتصاد والتسويق والزراعة وغيرها. برؤية تهدف إلى أن نصبح مزوداً عالمياً لبيانات الأبحاث، يتم دعم WDU من قبل فريق مهني يتمتع بخبرة تزيد عن 10 سنوات. يقع مقرنا في بوغور، وقد اكتسبنا ثقة العديد من الوكالات الحكومية والخاصة للتعامل مع مشاريع استشارية متنوعة، من الأبحاث إلى تنظيم الفعاليات.',
    'about.intro_content': 'تأسست Wahana Data Utama في عام 2006، ونمت لتصبح شركة رائدة في تقديم خدمات الأبحاث والبيانات في إندونيسيا مع رؤية "البيانات هي عملنا". نحن ملتزمون بأن نكون رواداً في حلول البيانات القائمة على الأبحاث من خلال الاستفادة من أحدث التقنيات، مثل تحليلات البيانات الضخمة، وتنفيذ المسوح، وإنترنت الأشياء (IoT)، لتقديم خدمات ذات صلة وتنافسية عالمياً في عصر الثورة الصناعية 5.0.<br/><br/>يقع مقرنا في Graha Nurul Menteng، بوغور، ونحن ندمج الابتكار الرقمي في الأبحاث الاجتماعية والسياسية، والدراسات البيئية، واقتصاديات التنمية، وصولاً إلى إدارة التسويق، ونقدم حلولاً سريعة ودقيقة قائمة على السحابة لاحتياجات متنوعة، بما في ذلك التعاونيات والشركات الصغيرة والمتوسطة، والأعمال الزراعية، والإعلان الرقمي. من خلال تطبيق أحدث التقنيات مثل التعلم الآلي للتحليل التنبئي، ندعم العملاء في مواجهة تحديات الأعمال الحديثة وخلق مزايا تنافسية مستدامة.',
    'about.pro_content': 'تأسست شركتنا على يد محترفين ذوي خبرة مع تخصص يزيد عن عقد من الزمان، ونحن نبني أساساً متيناً للشركة في كل جانب تشغيلي، من التخطيط والتنفيذ والإشراف إلى التقييم، باستخدام مناهج منهجية قائمة على التكنولوجيا الحديثة. يقوم خبراؤنا المدربون والمعتمدون باستمرار بتحسين كفاءاتهم من خلال التعليم والتدريب الرقمي، بما في ذلك الأبحاث واستخدام برامج التحليل المتقدمة.<br/><br/>كشريك استراتيجي للوكالات الحكومية والاشخاص، أثبتنا قدراتنا من خلال إكمال العديد من المشاريع الاستشارية المعقدة ومتعددة الأبعاد، والتي تغطي أبحاث اتجاهات السوق العالمية، والتدريب المهني القائم على التكنولوجيا، وصولاً إلى تنظيم الفعاليات المدعوم بالمنصات الرقمية.<br/><br/>مع تكامل الحلول المستدامة لمواجهة التحديات العالمية، والتحول الرقمي، والمرونة الاقتصادية، نستخدم البيانات كأصل استراتيجي لدعم التنمية الوطنية والدولية. في عام 2025، نظل ملتزمين بأن نكون شريكاً موثوقاً يجلب الابتكار والتغيير الكبير في منظومة تعتمد على البيانات وموجهة نحو المستقبل.',
    'role.KOMISARIS UTAMA': 'رئيس مجلس الإدارة',
    'role.DIREKTUR UTAMA': 'المدير العام',
    'role.DIREKTUR': 'مدير',
    'services.title.Riset Pasar': 'أبحاث السوق',
    'services.desc.Riset Pasar': 'استكشف فرصاً جديدة وافهم اتجاهات السوق من خلال أبحاث سوق متعمقة.',
    'services.title.Riset Data': 'أبحاث البيانات',
    'services.desc.Riset Data': 'معالجة البيانات الأولية والثانوية لتوليد رؤى استراتيجية.',
    'services.title.Analisis Data': 'تحليل البيانات',
    'services.desc.Analisis Data': 'تحويل البيانات الخام إلى أصول استراتيجية من خلال معالجة وتحقق متقدمين.',
    'services.title.Survei': 'استطلاع',
    'services.desc.Survei': 'جمع بيانات ميدانية دقيقة بمنهجيات علمية مجربة.',
    'services.title.Event Organizer': 'منظم فعاليات',
    'services.desc.Event Organizer': 'تنظيم فعاليات احترافي يركز على التفاصيل والتأثير الذي لا ينسى.',
    'services.title.Konsultasi IT': 'استشارات تكنولوجيا المعلومات',
    'services.desc.Konsultasi IT': 'استشارات تقنية استراتيجية لتحسين البنية التحتية الرقمية لأعمالك.'
  },
  fr: {
    'login.welcome': 'Bon retour.',
    'login.subtitle': 'Accédez à votre portail de gestion de données',
    'login.email_label': 'Identité e-mail',
    'login.password_label': 'Jeton de sécurité',
    'login.remember_me': 'Faire confiance à cet appareil',
    'login.forgot_password': 'Récupération',
    'login.submit': 'Authentifier l\'accès',
    'login.processing': 'Autorisation en cours...',
    'login.footer': 'Portail Sécurisé © 2026 Wahana Data Utama',
    'login.error': 'E-mail ou mot de passe invalide.',
    'common.loading': 'Veuillez patienter...',
    'common.intelligence': 'WDU Intelligence',
    'common.data_business': 'LES DONNÉES SONT NOTRE MÉTIER.',
    'common.empowering': 'Donner aux décideurs les moyens d\'agir grâce à des informations en temps réel et des analyses avancées depuis 2006.',
    'common.years_exp': 'Années d\'Exp',
    'common.projects': 'Projets',
    'common.analytics': 'Analyses 24/7',
    'nav.home': 'Accueil',
    'nav.about': 'À propos',
    'nav.services': 'Services',
    'nav.experience': 'Expérience',
    'nav.contact': 'Contact',
    'nav.download_profile': 'Profil Société',
    'footer.address': 'Adresse du bureau',
    'footer.contact': 'Contactez-nous',
    'footer.social': 'Réseaux Sociaux',
    'footer.privacy': 'Confidentialité',
    'footer.terms': 'Conditions',
    'footer.cookies': 'Cookies',
    'contact.hero_title': 'CONTACTEZ-NOUS',
    'contact.intro_title': 'Commençons quelque chose de grand ensemble.',
    'contact.hero_label': 'Intelligence Éditoriale',
    'contact.address_label': 'Adresse du bureau',
    'contact.email_label': 'E-mail',
    'contact.phone_label': 'Téléphone',
    'contact.form_title': 'Envoyer un message',
    'contact.success_title': 'Merci !',
    'contact.success_message': 'Votre message a été envoyé avec succès. Nous vous contacterons bientôt.',
    'contact.send_again': 'Envoyer un autre message',
    'contact.full_name': 'Nom complet',
    'contact.business_email': 'E-mail professionnel',
    'contact.phone_number': 'Numéro de téléphone',
    'contact.message': 'Message',
    'contact.message_placeholder': 'Comment pouvons-nous aider votre entreprise aujourd\'hui ?',
    'contact.sending': 'Envoi en cours...',
    'contact.send_button': 'Envoyer le message maintenant',
    'contact.privacy_note': 'Vos données sont stockées en toute sécurité conformément à notre politique de confidentialité.',
    'contact.hero_description': 'Nous sommes ici pour écouter votre vision et fournir des solutions technologiques adaptées. N\'hésitez pas à nous contacter pour une consultation initiale ou simplement pour poser des questions sur nos services.',
    'contact.intro_description': 'Notre équipe d\'experts est prête à répondre rapidement à toutes vos questions concernant la transformation numérique et la gestion intelligente des données.',
    'experience.hero_title': 'NOTRE EXPÉRIENCE',
    'experience.intro_title': 'Bâtir la confiance grâce à des preuves réelles.',
    'home.hero_title': 'Données Unifiées, Solutions Intelligentes | Résultats Maximaux',
    'home.hero_content': 'Confiez vos besoins en recherche, analyse de données et technologie à Wahana Data Utama. Nous transformons les données en informations précieuses et en solutions pratiques qui vous aident à acquérir un avantage concurrentiel à l\'ère numérique.',
    'home.intro_title': 'Une vaste expérience soutenue par une équipe professionnelle compétente.',
    'home.stats_projects': 'Projets Terminés',
    'home.stats_clients': 'Clients Satisfaits',
    'home.stats_efficiency': 'Efficacité des Données',
    'home.stats_support': 'Support 24/7',
    'home.services_title': 'Nos Services',
    'home.services_subtitle': 'Solutions de Données Intégrées',
    'home.services_content': 'Wahana Data Utama s\'engage à aider votre entreprise et votre organisation à gérer, analyser et utiliser les données de manière optimale.',
    'home.trust_title': 'La Confiance des Clients en Nous',
    'home.trust_subtitle': 'Avec 18 ans d\'expérience, nous construisons des collaborations stratégiques pour les organisations gouvernementales et le secteur privé.',
    'home.gallery_subtitle': 'Portraits de nos activités et collaborations',
    'home.gallery_quote': '"La précision des données est notre promesse, la collaboration est notre force."',
    'about.mission_title': 'Notre Mission pour Vous',
    'about.mission_desc': 'Engagé à fournir des solutions de données avec intégrité et un large impact pour le progrès de votre entreprise.',
    'about.vision_label': 'Vision',
    'about.vision_text': 'Être une société mondiale de fourniture de données de recherche/enquête.',
    'about.mission_label': 'Mission',
    'about.mission_1': 'Mener des recherches, des enquêtes et des études crédibles selon les règles scientifiques pour produire des données exacter, précises et fiables.',
    'about.mission_2': 'Organiser une activité de manière exacte, précise et fiable.',
    'about.mission_3': 'Être une entreprise créative pleine d\'innovation, de solutions et d\'idées.',
    'about.pillar_1_title': 'Crédibilité Scientifique',
    'about.pillar_1_desc': 'Mener des recherches, des enquêtes et des études crédibles selon les règles scientifiques.',
    'about.pillar_2_title': 'Précision Opérationnelle',
    'about.pillar_2_desc': 'Organiser une activité de manière exacte, précise et fiable.',
    'about.pillar_3_title': 'Innovation Créative',
    'about.pillar_3_desc': 'Être une entreprise créative pleine d\'innovation, de solutions et d\'idées.',
    'about.leadership_label': 'Notre Leadership',
    'about.directors_title': 'Conseil d\'Administration',
    'experience.track_record': 'NOTRE PARCOURS',
    'experience.headquarter': 'Siège de WDU',
    'experience.quality_assured': 'Qualité Garantie',
    'experience.data_accurate': 'Données précises pour les décisions stratégiques.',
    'experience.milestones_title': 'Jalons',
    'experience.milestones_subtitle': 'Partenaires Stratégiques et Collaboration Nationale',
    'experience.partners_count': 'Partenaires',
    'experience.syncing': 'Synchronisation des données partenaires...',
    'services.intro_subtitle': 'Nos Services',
    'services.intro_title': 'Explorez diverses solutions de pointe en utilisant nos services !',
    'services.intro_description': 'Nous sommes heureux de vous aider à répondre à vos besoins grâce aux meilleurs services que nous proposons.',
    'services.no_services': 'Aucun service n\'est disponible pour le moment.',
    'services.data_business_desc': 'Les données ne sont pas seulement des chiffres pour nous, mais le fondement de la création des meilleures solutions. Grâce à notre expertise et à notre technologie, nous apportons des informations qui stimulent la croissance et l\'innovation.',
    'home.intro_content': 'Wahana Data Utama a été fondée en 2006 en tant que société de recherche et d\'enquête se concentrant sur les domaines socio-politiques, économiques, de marketing, agricoles et autres. Avec la vision de devenir un fournisseur mondial de données de recherche, WDU est soutenu par une équipe professionnelle de plus de 10 ans d\'expérience. Basés à Bogor, nous avons gagné la confiance de diverses agences gouvernementales et privées pour gérer divers projets de conseil, de la recherche à l\'organisation d\'événements.',
    'about.intro_content': 'Wahana Data Utama a été fondée en 2006 et est devenue une entreprise leader dans la fourniture de services de recherche et de données en Indonésie avec la vision "Data Is Our Business". Nous nous engageons à être un pionnier dans les solutions de données basées sur la recherche en utilisant les dernières technologies, telles que l\'analyse des mégadonnées, l\'exécution d\'enquêtes et l\'Internet des objets (IoT), pour fournir des services pertinents et compétitifs à l\'échelle mondiale à l\'ère de la révolution industrielle 5.0.<br/><br/>Basés à Graha Nurul Menteng, Bogor, nous intégrons l\'innovation numérique dans la recherche socio-politique, les études environnementales, l\'économie du développement, jusqu\'à la gestion du marketing, et proposons des solutions basées sur le cloud rapides et précises pour divers besoins, notamment les coopératives et les PME, l\'agrobusiness et la publicité numérique. Grâce à l\'application de technologies de pointe comme l\'apprentissage automatique pour l\'analyse prédictive, nous aidons nos clients à faire face aux défis commerciaux modernes et à créer des avantages concurrentiels durables.',
    'about.pro_content': 'Fondée par des professionnels expérimentés ayant plus d\'une décennie de spécialisation, nous construisons une base solide dans chaque aspect opérationnel, de la planification, l\'exécution, la supervision à l\'évaluation, en utilisant des approches méthodologiques basées sur la technologie moderne. Nos experts formés et certifiés améliorent continuellement leurs compétences grâce à l\'éducation et à la formation numériques, y compris la recherche et l\'utilisation de logiciels d\'analyse avancés.<br/><br/>En tant que partenaire stratégique pour les agences gouvernementales et privées, nous avons prouvé nos capacités en menant à bien divers projets de conseil complexes et multidimensionnels, couvrant la recherche sur les tendances du marché mondial, la formation professionnelle basée sur la technologie, jusqu\'à l\'organisation d\'événements soutenue par des plateformes numériques.<br/><br/>Avec l\'intégration de solutions durables pour faire face aux défis mondiaux, à la transformation numérique et à la résilience économique, nous utilisons les données comme un atout stratégique pour soutenir le développement national et international. En 2025, nous restons déterminés à être un partenaire de confiance qui apporte l\'innovation et des changements significatifs dans un écosystème axé sur les données et orienté vers l\'avenir.',
    'role.KOMISARIS UTAMA': 'Président du Conseil',
    'role.DIREKTUR UTAMA': 'Directeur Général',
    'role.DIREKTUR': 'Directeur',
    'services.title.Riset Pasar': 'Étude de Marché',
    'services.desc.Riset Pasar': 'Explorez de nouvelles opportunités et comprenez les tendances du marché grâce à une étude de marché approfondie.',
    'services.title.Riset Data': 'Recherche de Données',
    'services.desc.Riset Data': 'Traitement des données primaires et secondaires pour générer des informations stratégiques.',
    'services.title.Analisis Data': 'Analyse de Données',
    'services.desc.Analisis Data': 'Transformer les données brutes en actifs stratégiques grâce à un traitement et une validation avancés.',
    'services.title.Survei': 'Sondage',
    'services.desc.Survei': 'Collecte précise de données de terrain avec des méthodologies scientifiques testées.',
    'services.title.Event Organizer': 'Organisateur d\'Événements',
    'services.desc.Event Organizer': 'Organisation d\'événements professionnels axée sur le détail et un impact mémorable.',
    'services.title.Konsultasi IT': 'Conseil en TI',
    'services.desc.Konsultasi IT': 'Conseil technologique stratégique pour optimiser l\'infrastructure numérique de votre entreprise.'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const savedLang = localStorage.getItem('language');
    return (savedLang as Language) || 'id';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const toggleLanguage = () => {
    setLanguageState((prev) => {
      if (prev === 'id') return 'en';
      if (prev === 'en') return 'jp';
      if (prev === 'jp') return 'zh';
      if (prev === 'zh') return 'es';
      if (prev === 'es') return 'ar';
      if (prev === 'ar') return 'fr';
      return 'id';
    });
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
